### PR TITLE
Plyr Polyfilled Version

### LINKED ISSUE #138: Transpile plyr import IE11 issue
Can a conditional option be added to configure support for IE11 with the build transpile as seen in this example: https://github.com/sampotts/plyr/issues/890#issuecomment-515765128?

**replace**
`import Plyr from 'plyr';`
**with...**
`import Plyr from 'plyr/dist/plyr.polyfilled.js';`

Currently plyr needs polyfill support for IE11 and with the vue-plyr component, I cannot get the dependency to work correctly unless someone knows of another way?

Note: I attempted to manually transpile the dependency in my nuxt config but did not seem to resolve..
```
build: {
    transpile: ['vue-plyr', 'plyr'],
    babel: {
      presets({ envName }) {
        const envTargets = {
          client: { browsers: ["last 2 versions"], ie: 11 },
          server: { node: "current" }
        }
        return [
          [
            "@nuxt/babel-preset-app",
            {
              targets: envTargets[envName]
            }
          ]
        ]
      }
    }
}
```
I am getting this error thrown in IE:
`Assignment to read-only properties is not allowed in strict mode`

The transpile did however fix IE11 issues with arrow syntax and spread operator.

### PR DESCRIPTION
**Pull request by devotoare**
Add a bundle for the polyfilled version of Plyr.

resolve #138

### CODE REVIEW

**Comment by redxtech** [comment]
Why did you remove dist from the .gitignore?

Also, if you want a polyfilled build for this component, I would recommend running the polyfill on your end in order to get it right for your setup.

**Comment by redxtech** [comment]
Also take a look at this:
https://github.com/redxtech/vue-plyr/issues/138#issuecomment-583529960
> ```ts
> build: {
>   extend(config) {
>     config.resolve.alias['plyr$'] = 'plyr/dist/plyr.polyfilled.js'
>   },
> },
> ```

**Comment by devotoare** [comment]
> Why did you remove dist from the .gitignore?
> 
> Also, if you want a polyfilled build for this component, I would recommend running the polyfill on your end in order to get it right for your setup.



> Why did you remove dist from the .gitignore?
> 
> Also, if you want a polyfilled build for this component, I would recommend running the polyfill on your end in order to get it right for your setup.

Added it for a local thing it wasn't supposed to be part of the PR. The comment in 138 didn't mean anything to me at the time either. Something in the docs at least would go a long way to knowing where in which file something should go in.

**Comment by redxtech** [comment]
Ah ok makes sense. Sorry about the confusion, I'll add something to the docs to make this more clear.

**Pull request closed without merging**
