### PR TITLE
Fix build with updating to bili@4

### PR DESCRIPTION
**Pull request by zcuric**
### This PR
- [x] Solves #60 
- [x] Updates `bili` to version 4 
- [x] Optimizes the build

### CODE REVIEW

**Comment by dappiu** [comment]
I'd like to see this merged, I'm actively using this changeset on a fork of the package in my projects.

**Comment by zcuric** [comment]
@dappiu you can use my fork until this gets merged. https://github.com/zcuric/plyrue

**Comment by redxtech** [comment]
Hey there! Thanks a ton for this - I've been really backed up lately and haven't been able to put as much time into this project as is needed.

This looks like a really good addition that would solve a bunch of problems, so I will merge it.

Before doing so, would you be able to tell me what changing from `preset: '@vue/app'` to `preset: '@babel/preset-env'` does? Does `babel-env` do something more than vue does not?

Thanks :)

**Comment by zcuric** [comment]
@redxtech For some odd reason when using `preset: '@vue/app'` code wouldn't transpile correctly. 
I think the reason is becasue of `bili`, but I'm not quite sure. I actually omitted that babel config in my own fork https://github.com/zcuric/plyrue. 

 Before merging, please double check everything.  I did this in haste, we needed to release our product to production asap and because of that I went with my own fork.

**Comment by zcuric** [comment]
I've update the PR wit more commits.

**Comment by redxtech** [comment]
Sorry for the delays - I should be able to get to this in a few weeks.

**Comment by zcuric** [comment]
I've made updates to my version of this plugin, you can check it out: https://github.com/zcuric/plyrue

**Comment by redxtech** [comment]
sorry for the delay. Merging now.

**Pull request merged**
