### PR TITLE
Upgrade to Plyr 3.0 - Fixes Fullscreen Issue on iPad

### PR DESCRIPTION
**Pull request by rebz**
Requesting an upgrade of this package to use plyr 3.0.

### CODE REVIEW

**Comment by redxtech** [comment]
I have tried to upgrade to plyr 3 before, and it hasn't worked. That was before v3 was officially released. When I get home I will take a look at this and publish an update as soon as I see it working.

**Comment by redxtech** [comment]
After taking a quick look at this, I will be closing this PR after a small amount of time as updating to plyr 3.0 requires more than just changing the version in package.json. There are a few API changes that I will get to tonight.

**Comment by redxtech** [comment]
Ok, I have added this in the develop branch. I will push it to NPM once I get a few small bugs fixed.
Thanks for bringing this up.

**Comment by redxtech** [comment]
@rebz will update this and push to npm once I have SSR supported

**Comment by rebz** [comment]
@redxtech

Thank you for doing this. I noticed the API issue after I made the commit request.

**Comment by redxtech** [comment]
no problem \:)

**Pull request closed without merging**
