### PR TITLE
fix: can't receive any events

### PR DESCRIPTION
**Pull request by joe-re**
It can't emit any events because we have forgotten let event callback function receive event argument.

### CODE REVIEW

**Comment by jwjcmw** [comment]
I see what you are saying there, but not being a js expert...why is it working for me?...
capture

**Comment by joe-re** [comment]
umm, I thought I couldn't work it...
but surely it looks good as far as look your capture.
OK, I'll try that again and check it.

**Comment by redxtech** [comment]
sorry i haven't had time to look into this. give me a few hours and I'll take a look at this then.

**Comment by redxtech** [comment]
Ok so it appears as if JS automatically passes the args for us. If this becomes a problem in the future we can look into it again, but it appears to be fine now.

**Pull request closed without merging**
